name: CI

on:
  workflow_call:
    inputs:
      workdir:
        required: false
        type: string
        default: "."
      extrasteps:
        required: false
        type: string
        default: ""
  ## Disable CI in this public repo until after a self-hosted runner can be setup safely
  # pull_request:
  #   branches: [main]

jobs:
  build_fake_builds:
    name: Build Fake L4T Images
    runs-on: self-hosted
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout all git history

      - name: Run Optional Extra Steps
        if: ${{ inputs.extrasteps != null }}
        run: ${{ inputs.extrasteps }} ${{ inputs.workdir }}

      - name: Set up QEMU for multi-arch builds
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker buildx for multi-arch builds
        uses: docker/setup-buildx-action@v2

      # install required tools into host
      - name: Install required tools into host
        run: |
          sudo apt-get update && sudo apt-get install -y \
          pbzip2

      - name: Run unit-test
        working-directory: ${{ inputs.workdir || '.' }}
        run: ./unit-tests/unit-test.sh
