name: CI

on:
  workflow_call:
  ## Disable CI in this public repo until after a self-hosted runner can be setup safely
  # pull_request:
  #   branches: [main]

jobs:
  build_fake_builds:
    name: Build Fake L4T Images
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # checkout all git history
      - name: Run unit-test
        run: ./unit-tests/unit-test.sh
